
(()=>{
const D=window.EILUNE_DATA; const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const catIcon={Lore:'◇',Characters:'♙',Factions:'✦',Places:'⌖',Bestiary:'△'};
const entries=D.entries; const byKey=new Map(entries.map(e=>[`${e.category}/${e.slug}`,e]));
function esc(s=''){return String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function route(){let h=location.hash.replace(/^#\/?/,'');if(!h)return {type:'home'};let p=h.split('/').filter(Boolean).map(decodeURIComponent);if(p[0]==='category'&&p[1])return{type:'category',category:p[1]};if(p[0]==='entry'&&p[1]&&p[2])return{type:'entry',category:p[1],slug:p[2]};return{type:'home'}}
function urlCat(c){return `#/category/${encodeURIComponent(c)}`}; function urlEntry(e){return `#/entry/${encodeURIComponent(e.category)}/${encodeURIComponent(e.slug)}`}
function nav(){const n=$('.topnav'); n.innerHTML=D.categories.map(c=>`<a class="nav-link" data-cat="${esc(c)}" href="${urlCat(c)}">${esc(c)}</a>`).join('');const m=$('.mobile-nav');m.innerHTML=`<a class="mobile-link home" href="#/"><span class="mi">✧</span>Codex</a>`+D.categories.slice(0,4).map(c=>`<a class="mobile-link" data-cat="${esc(c)}" href="${urlCat(c)}"><span class="mi">${catIcon[c]}</span>${esc(c)}</a>`).join('')+`<button class="mobile-link more" id="moreBtn"><span class="mi">☰</span>More</button>`;$('#moreBtn').onclick=()=>openSidebar();}
function setActive(c){$$('.nav-link,.mobile-link').forEach(x=>x.classList.remove('active')); if(!c){$('.mobile-link.home')?.classList.add('active')} else $$(`[data-cat="${CSS.escape(c)}"]`).forEach(x=>x.classList.add('active'));}
function sidebar(c,current){$('#sidebarCategory').textContent=c||'Codex';let html='';if(!c){html=`<div class="side-group"><div class="side-group-title">Archive</div>${D.categories.map(x=>`<a class="side-link" href="${urlCat(x)}"><span class="dot"></span>${esc(x)} <span style="margin-left:auto;color:#6f7480">${D.counts[x]}</span></a>`).join('')}</div>`}else{const groups=D.groupOrders[c]||[...new Set(entries.filter(e=>e.category===c).map(e=>e.group))];for(const g of groups){const list=entries.filter(e=>e.category===c&&e.group===g);if(!list.length)continue;html+=`<div class="side-group"><div class="side-group-title">${esc(g)}</div>${list.map(e=>`<a class="side-link ${current===e.slug?'active':''}" href="${urlEntry(e)}"><span class="dot"></span>${esc(e.name)}</a>`).join('')}</div>`}}$('#sidebarContent').innerHTML=html;}
function openSidebar(){const r=route();sidebar(r.category||null,r.slug||null);$('#sidebar').classList.add('open')}; $('#sidebarClose').onclick=()=>$('#sidebar').classList.remove('open');
function card(e,feature=false){return `<a href="${urlEntry(e)}" class="${feature?'feature-card':'entry-card'} ${e.hero?'':'no-image'}">${e.hero?`<img src="${esc(e.hero)}" alt="">`:''}<div class="card-content"><div class="card-kicker">${esc(e.category)} · ${esc(e.group)}</div><div class="card-title">${esc(e.name)}</div>${e.summary?`<div class="card-summary">${esc(e.summary)}</div>`:''}</div></a>`}
function home(){setActive(null);sidebar(null);const feat=D.featured.map(s=>entries.find(e=>e.slug===s)).filter(Boolean).slice(0,3);const ribbon=entries.find(e=>e.name==='The Ribbon');return `<section class="page"><div class="home-hero"><div><div class="eyebrow">Player Archive</div><h1 class="home-title">Eilune<span>Codex of a Changed World</span></h1><div class="rule"></div><p class="home-copy">A living reference for the places, people, powers and phenomena encountered across Eilune. Browse the archive by subject or search for anything by name.</p></div><div class="home-art">${ribbon?.hero?`<img src="${esc(ribbon.hero)}" alt="The Ribbon artwork">`:''}</div></div><div class="category-grid">${D.categories.map(c=>`<a class="category-card" href="${urlCat(c)}"><span class="cat-num">${catIcon[c]} &nbsp; ${String(D.counts[c]).padStart(2,'0')}</span><b>${esc(c)}</b><small>Open archive</small></a>`).join('')}</div><h2 class="section-title">From the Archive</h2><div class="feature-grid">${feat.map(e=>card(e,true)).join('')}</div></section>`}
function category(c){if(!D.categories.includes(c))return home();setActive(c);sidebar(c);const groups=D.groupOrders[c]||[...new Set(entries.filter(e=>e.category===c).map(e=>e.group))];let blocks='';for(const g of groups){const list=entries.filter(e=>e.category===c&&e.group===g);if(!list.length)continue;blocks+=`<section class="group-block"><h2>${esc(g)}</h2><div class="browse-grid">${list.map(e=>card(e)).join('')}</div></section>`}return `<section class="page"><div class="breadcrumb">Eilune Codex &nbsp; / &nbsp; <span>${esc(c)}</span></div><div class="category-header"><div><div class="eyebrow">Archive</div><h1>${esc(c)}</h1><p class="page-subtitle">${({Lore:'Histories, faiths, phenomena, traditions and stories recorded across Eilune.',Characters:'The rulers, leaders and notable figures who shape the age.',Factions:'Orders, guilds and powers whose influence reaches across the world.',Places:'Nations, settlements and wildernesses known to the party.',Bestiary:'Creatures, monsters and stranger things encountered or documented.'})[c]}</p></div><div class="category-count">${D.counts[c]} <small>entries</small></div></div><div class="rule"></div>${blocks}</section>`}
function listPanels(e){if(!e.lists?.length)return'';return e.lists.map(l=>`<section class="aside-card"><h3>${esc(l.label)}</h3>${l.items.map(i=>`<div class="fact">${i.name||i.tag||i.label?`<div class="fact-name">${esc(i.name||i.tag||i.label)}</div>`:''}${i.description?`<div class="fact-desc">${esc(i.description)}</div>`:''}${i.value?`<div class="fact-value">${esc(i.value)}</div>`:''}${i.current?`<div class="fact-value">${esc(i.current)}${i.max?` / ${esc(i.max)}`:''}</div>`:''}</div>`).join('')}</section>`).join('')}
function article(c,s){const e=byKey.get(`${c}/${s}`);if(!e)return home();setActive(c);sidebar(c,s);let meta=e.meta?.length?`<div class="meta-grid">${e.meta.map(m=>`<div class="meta-cell"><div class="meta-label">${esc(m.label)}</div><div class="meta-value">${esc(m.value)}</div></div>`).join('')}</div>`:'';let tags=[...(e.mainTag?[e.mainTag]:[]),...(e.tags||[])];return `<article class="page"><div class="breadcrumb"><a href="#/">Eilune Codex</a> &nbsp; / &nbsp; <a href="${urlCat(c)}">${esc(c)}</a> &nbsp; / &nbsp; <span>${esc(e.group)}</span></div><header class="article-head"><div><div class="eyebrow">${esc(e.group)}</div><h1>${esc(e.name)}</h1>${e.subtitle?`<p class="page-subtitle">${esc(e.subtitle)}</p>`:''}${tags.length?`<div class="tag-row">${[...new Set(tags)].map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`:''}</div>${e.hero?`<div class="article-image"><img src="${esc(e.hero)}" alt="${esc(e.name)}"></div>`:''}</header>${meta}<div class="rule"></div><div class="article-layout"><div class="article-body">${e.content||'<p>No public text has been recorded for this entry yet.</p>'}</div><aside class="article-aside">${listPanels(e)}</aside></div></article>`}
function render(){const r=route();let h=r.type==='home'?home():r.type==='category'?category(r.category):article(r.category,r.slug);$('#app').innerHTML=h;$('#app').focus({preventScroll:true});window.scrollTo(0,0);if(innerWidth<761)$('#sidebar').classList.remove('open')}

// Search
const dlg=$('#searchDialog'), input=$('#searchInput'), results=$('#searchResults');
function openSearch(){if(!dlg.open)dlg.showModal();setTimeout(()=>input.focus(),0);search('')};function closeSearch(){dlg.close()}
$('#searchButton').onclick=openSearch;window.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea/i.test(document.activeElement.tagName)){e.preventDefault();openSearch()}if(e.key==='Escape'&&dlg.open)closeSearch()});
function search(q){q=q.trim().toLowerCase();let list;if(!q)list=entries.slice(0,12);else{let words=q.split(/\s+/);list=entries.map(e=>{let hay=(e.name+' '+e.category+' '+e.group+' '+e.tags.join(' ')+' '+e.mainTag+' '+e.summary).toLowerCase();let score=words.reduce((n,w)=>n+(e.name.toLowerCase().includes(w)?8:0)+(e.group.toLowerCase().includes(w)?4:0)+(hay.includes(w)?1:0),0);return{e,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,20).map(x=>x.e)}results.innerHTML=list.length?list.map(e=>`<a class="search-result" href="${urlEntry(e)}"><span><b>${esc(e.name)}</b><small>${esc(e.group)}</small></span><em>${esc(e.category)}</em></a>`).join(''):`<div class="empty-state">Nothing in the archive matches that search.</div>`;$$('.search-result').forEach(a=>a.onclick=()=>closeSearch())}
input.addEventListener('input',()=>search(input.value));
nav();window.addEventListener('hashchange',render);render();
})();
